safe: false
source: .
destination: ./_site
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']
sass:
  style: uncompressed
gems:
  - jekyll-bootstrap-sass

bootstrap:
  assets: true
  
url: http://web.cs.ucla.edu
baseurl: /classes/spring17/cs118

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CS118: Computer Network Fundamentals - Spring 2017 (UCLA)"
description: 
author: Alexander Afanasyev
email:

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Syllabus
  link: /syllabus.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Acio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
# - name: Project 3 (Riddikulus)
#   link: /project-3.html

course_info:
  times: Mondays/Wednesdays 8am-9:50am
  room: ROLFE 1200
  name: Alex Afanasyev
  contact: aa at cs.ucla.edu
  office_hours: Wednesday 5:30pm-6:30pm (BH 4809), other times by appointment 

  homeworks_due: Wednesday of the week following the assignment, 11pm
  midterm: TBD
  
  final: Wednesday, TBD, 8am-9:50am
  final_room: ROLFE 1200

  sections:
    - times: Friday / 10:00am-11:50am
      room: BH 5264
      name: Seungbae Kim
      contact: sbkim at cs.ucla.edu
      office_hours: TBD

    - times: Friday / 12:00pm-1:50pm
      room: BH 5264
      name: Haitao Zhang
      contact: haitao at cs.ucla.edu
      office_hours: TBD
    
    - times: Friday / 2:00pm-3:50pm
      room: BH 5249
      name: Zengwen Yuan
      contact: zyuan at cs.ucla.edu
      office_hours: Wednesday 10:00am-12:00pm

    - times: Friday / 8:00am-9:50am
      room: GEOLOGY 4660
      name: Pranav Sodhani
      contact: sodhanipranav at cs.ucla.edu
      office_hours: TBD

  projects:
    - deadline: TBD
    - deadline: TBD
    - deadline: TBD
