safe: false
source: .
destination: ./_site
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']
sass:
  style: uncompressed
kramdown:
  toc_levels: "2,3"

url: http://web.cs.ucla.edu
baseurl: /classes/spring17/cs118

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CS118: Computer Network Fundamentals - Spring 2017 (UCLA)"
description:
author: Alexander Afanasyev
email:

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Syllabus
  link: /syllabus.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Acio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
- name: Project 3 (Riddikulus)
  link: /project-3.html

course_info:
  times: Mondays/Wednesdays, 8am-9:50am
  room: ROLFE 1200
  name: Alex Afanasyev
  contact: aa at cs.ucla.edu
  office_hours: Wednesdays, 5:30pm-6:30pm (BH 4809), other times by appointment

  homeworks_due: Wednesday of the week following the assignment, 11pm
  midterm: <del>Wednesday, May 3, 2017, 8am-9:50am</del> <br/> Monday, May 1, 2017, 8am-9:50am

  final: Monday, June 12, 2017, 6:30pm-9:30pm
  final_room: TBD

  sections:
    - times: Fridays / 10:00am-11:50am
      room: BH 5264
      name: Seungbae Kim
      contact: sbkim at cs.ucla.edu
      office_hours: Wednesdays / 3:30pm-5:30pm <b>(BH 2432)</b>

    - times: Fridays / 12:00pm-1:50pm
      room: BH 5264
      name: Haitao Zhang
      contact: haitao at cs.ucla.edu
      office_hours: Tuesdays / 2:00pm-4:00pm <b>(BH 2432)</b>

    - times: Fridays / 2:00pm-3:50pm
      room: BH 5249
      name: Zengwen Yuan
      contact: zyuan at cs.ucla.edu
      office_hours: Wednesdays / 10:00am-12:00pm <b>(BH 2432)</b>

    - times: Fridays / 8:00am-9:50am
      room: GEOLOGY 4660
      name: Pranav Sodhani
      contact: sodhanipranav at cs.ucla.edu
      office_hours: Mondays / 10:00am-12:00pm <b>(BH 2432)</b>

  projects:
    - deadline: Sunday, April 23, 2017, 11pm PDT
    - deadline: Sunday, May 21, 2017, 11pm PDT
    - deadline: Sunday, June 11, 2017, 11pm PDT
